Add KB article link for error fix
If Pulp 2 to Pulp 3 migration fails with error "NoMethodError:
undefined method `link?' for nil:NilClass", there is a KB article on
the customer portal that will show the user how to fix the error. This
link was added to the Pre-Migration checks.