Manually configure git when syncing templates (#3243)
* Manually add Git config for template sync

Without these steps, `sudo -u foreman git config --global` fails with
this error:

error: could not lock config file /usr/share/foreman/.gitconfig: Permission denied

* Minor edits and clarifications

---------

Co-authored-by: Maximilian Kolb <mail@maximilian-kolb.de>
(cherry picked from commit 9db6c8b52a4cfc2b0c4502cfa498675ec3eb5c44)