Use `hammer flatpak-remote remote-repository list` to list contents (#3879)
Otherwise things fail:

    # hammer flatpak-remote repository list --flatpak-remote-id=2
    Error: No such sub-command 'repository'.

    See: 'hammer flatpak-remote --help'.

Fixes: 2a0e9d2a746b6eaecfc48c7df8dc7bd782b68fae
(cherry picked from commit 55acea594b17f536590cf0eefeb48077a8d4d689)